import 'models.dart';

const _sizes = ['XS', 'S', 'M', 'L', 'XL', 'XXL'];

const List<Product> allProducts = [
  // ── Lehenga Collection ────────────────────────────────────────────────────
  Product(
    id: '1', name: 'Lehenga 1', price: 10000, originalPrice: 13000, discount: 23,
    imageAsset: 'assets/images/N 1.jpg',
    images: ['assets/images/N 1.jpg', 'assets/images/N 1 - Copy.jpg'],
    category: 'Lehenga', material: 'Pure Silk',
    description: 'Exquisite hand-crafted lehenga adorned with intricate zari embroidery. Perfect for weddings and festive celebrations.',
    colors: ['Red', 'Maroon', 'Pink'], sizes: _sizes, stock: 8, rating: 4.5, reviewCount: 24,
    tags: ['lehenga', 'wedding', 'silk', 'zari'],
  ),
  Product(
    id: '2', name: 'Lehenga 2', price: 9000, originalPrice: 11000, discount: 18,
    imageAsset: 'assets/images/N 8.jpg',
    images: ['assets/images/N 8.jpg', 'assets/images/N 7.jpg'],
    category: 'Lehenga', material: 'Georgette',
    description: 'Stunning georgette lehenga with delicate floral embroidery, ideal for sangeet and mehendi functions.',
    colors: ['Blue', 'Teal', 'Purple'], sizes: _sizes, stock: 5, rating: 4.2, reviewCount: 18,
    tags: ['lehenga', 'party', 'georgette'],
  ),
  Product(
    id: '3', name: 'Lehenga 3', price: 9000, originalPrice: 10500, discount: 14,
    imageAsset: 'assets/images/n2.jpeg.jpg',
    images: ['assets/images/n2.jpeg.jpg', 'assets/images/n3.jpg'],
    category: 'Lehenga', material: 'Net',
    description: 'Elegant net lehenga with mirror work and sequin detailing. A showstopper for any celebration.',
    colors: ['Green', 'Yellow', 'Orange'], sizes: _sizes, stock: 3, rating: 4.0, reviewCount: 12,
    tags: ['lehenga', 'traditional', 'net', 'mirror-work'],
  ),
  Product(
    id: '4', name: 'Lehenga 4', price: 9000, originalPrice: 12000, discount: 25,
    imageAsset: 'assets/images/n17.jpg',
    images: ['assets/images/n17.jpg', 'assets/images/n16.jpg'],
    category: 'Lehenga', material: 'Velvet',
    description: 'Royal velvet lehenga with gold embroidery borders. An absolute bridal statement piece.',
    colors: ['Royal Blue', 'Wine', 'Black'], sizes: _sizes, stock: 2, rating: 4.8, reviewCount: 31,
    tags: ['lehenga', 'bridal', 'velvet', 'gold'],
  ),
  Product(
    id: '5', name: 'Lehenga 5', price: 9000, originalPrice: 10000, discount: 10,
    imageAsset: 'assets/images/n21.jpg',
    images: ['assets/images/n21.jpg', 'assets/images/n22.jpg'],
    category: 'Lehenga', material: 'Chiffon',
    description: 'Flowing chiffon lehenga with digital print and embellished hem. Perfect for receptions.',
    colors: ['Pink', 'Coral', 'Mint'], sizes: _sizes, stock: 7, rating: 4.3, reviewCount: 15,
    tags: ['lehenga', 'chiffon', 'printed'],
  ),
  Product(
    id: '6', name: 'Lehenga 6', price: 9000, originalPrice: 11000, discount: 18,
    imageAsset: 'assets/images/N 1.jpg',
    images: ['assets/images/N 1.jpg', 'assets/images/N 2.jpg'],
    category: 'Lehenga', material: 'Cotton Silk',
    description: 'Lightweight cotton silk lehenga for day functions and casual festive wear.',
    colors: ['Peach', 'Cream', 'Lavender'], sizes: _sizes, stock: 10, rating: 3.9, reviewCount: 9,
    tags: ['lehenga', 'casual', 'cotton'],
  ),
  Product(
    id: '7', name: 'Lehenga 7', price: 9000, originalPrice: 10500, discount: 14,
    imageAsset: 'assets/images/N 2.jpg',
    images: ['assets/images/N 2.jpg', 'assets/images/N 3.jpg'],
    category: 'Lehenga', material: 'Art Silk',
    description: 'Semi-stitched art silk lehenga with heavy embroidery. Customize for a perfect fit.',
    colors: ['Purple', 'Blue', 'Green'], sizes: _sizes, stock: 6, rating: 4.0, reviewCount: 7,
    tags: ['lehenga', 'semi-stitched', 'art-silk'],
  ),
  Product(
    id: '8', name: 'Lehenga 8', price: 9000, originalPrice: 10000, discount: 10,
    imageAsset: 'assets/images/N 3.jpg',
    images: ['assets/images/N 3.jpg', 'assets/images/N 4.jpg'],
    category: 'Lehenga', material: 'Crepe',
    description: 'Smooth crepe lehenga with delicate thread work and a modern silhouette.',
    colors: ['Red', 'Pink', 'Orange'], sizes: _sizes, stock: 8, rating: 4.1, reviewCount: 11,
    tags: ['lehenga', 'crepe', 'thread-work'],
  ),
  Product(
    id: '9', name: 'Lehenga 9', price: 9000, originalPrice: 11500, discount: 22,
    imageAsset: 'assets/images/N 4.jpg',
    images: ['assets/images/N 4.jpg', 'assets/images/N 5.jpg'],
    category: 'Lehenga', material: 'Banarasi Silk',
    description: 'Traditional Banarasi silk lehenga with woven gold motifs. An heirloom piece.',
    colors: ['Red', 'Maroon', 'Golden'], sizes: _sizes, stock: 4, rating: 4.6, reviewCount: 22,
    tags: ['lehenga', 'banarasi', 'silk', 'gold'],
  ),
  Product(
    id: '10', name: 'Lehenga 10', price: 9000, originalPrice: 10000, discount: 10,
    imageAsset: 'assets/images/N 5.jpg',
    images: ['assets/images/N 5.jpg', 'assets/images/N 6.jpg'],
    category: 'Lehenga', material: 'Cotton',
    description: 'Classic traditional lehenga with bandhani print and gota patti work.',
    colors: ['Yellow', 'Orange', 'Green'], sizes: _sizes, stock: 10, rating: 4.1, reviewCount: 19,
    tags: ['lehenga', 'traditional', 'bandhani'],
  ),
  Product(
    id: '11', name: 'Lehenga 11', price: 9000, originalPrice: 10500, discount: 14,
    imageAsset: 'assets/images/N 6.jpg',
    images: ['assets/images/N 6.jpg', 'assets/images/N 1.jpg'],
    category: 'Lehenga', material: 'Organza',
    description: 'Contemporary designer lehenga with abstract prints and minimal embroidery.',
    colors: ['White', 'Ivory', 'Blush'], sizes: _sizes, stock: 5, rating: 4.4, reviewCount: 17,
    tags: ['designer', 'modern', 'organza'],
  ),
  // ── Bridal Collection ─────────────────────────────────────────────────────
  Product(
    id: '12', name: 'Choli', price: 9000, originalPrice: 10000, discount: 10,
    imageAsset: 'assets/images/b1.jpg',
    images: ['assets/images/b1.jpg', 'assets/images/b2.jpg'],
    category: 'Bridal', material: 'Silk Brocade',
    description: 'Beautifully crafted bridal choli with heavy stone and bead work. Comes with matching dupatta.',
    colors: ['Red', 'Maroon', 'Gold'], sizes: _sizes, stock: 4, rating: 4.7, reviewCount: 22,
    tags: ['choli', 'bridal', 'brocade', 'stone-work'],
  ),
  Product(
    id: '13', name: 'Saree Lehenga', price: 9000, originalPrice: 11000, discount: 18,
    imageAsset: 'assets/images/b2.jpg',
    images: ['assets/images/b2.jpg', 'assets/images/b3.jpg'],
    category: 'Bridal', material: 'Banarasi Silk',
    description: 'Traditional Banarasi silk saree-lehenga hybrid with woven gold motifs. An heirloom piece.',
    colors: ['Red', 'Pink', 'Purple'], sizes: _sizes, stock: 6, rating: 4.6, reviewCount: 28,
    tags: ['saree', 'lehenga', 'banarasi', 'silk'],
  ),
  Product(
    id: '14', name: 'Heavy Bride Lehenga', price: 9000, originalPrice: 14000, discount: 36,
    imageAsset: 'assets/images/b3.jpg',
    images: ['assets/images/b3.jpg', 'assets/images/b4.jpg'],
    category: 'Bridal', material: 'Pure Silk + Net',
    description: 'Grand bridal lehenga with 3D floral embroidery and crystal embellishments.',
    colors: ['Red', 'Pink', 'Ivory'], sizes: _sizes, stock: 2, rating: 5.0, reviewCount: 40,
    tags: ['bridal', 'heavy', '3D-embroidery'],
  ),
  Product(
    id: '15', name: 'Designer Lehenga', price: 9000, originalPrice: 13000, discount: 31,
    imageAsset: 'assets/images/b4.jpg',
    images: ['assets/images/b4.jpg', 'assets/images/b5.jpg'],
    category: 'Bridal', material: 'Organza',
    description: 'Contemporary designer lehenga with abstract prints and minimal embroidery. For the modern bride.',
    colors: ['White', 'Ivory', 'Blush'], sizes: _sizes, stock: 5, rating: 4.4, reviewCount: 17,
    tags: ['designer', 'modern', 'organza'],
  ),
  Product(
    id: '16', name: 'Sharara', price: 9000, originalPrice: 10500, discount: 14,
    imageAsset: 'assets/images/b5.jpg',
    images: ['assets/images/b5.jpg', 'assets/images/b6.jpg'],
    category: 'Bridal', material: 'Georgette',
    description: 'Traditional Mughal-inspired sharara with intricate embroidery and wide-flare pants.',
    colors: ['Blue', 'Green', 'Pink'], sizes: _sizes, stock: 8, rating: 4.1, reviewCount: 11,
    tags: ['sharara', 'traditional', 'mughal'],
  ),
  Product(
    id: '17', name: 'Velvet Sharara', price: 9000, originalPrice: 12000, discount: 25,
    imageAsset: 'assets/images/b6.jpg',
    images: ['assets/images/b6.jpg', 'assets/images/b7.jpg'],
    category: 'Bridal', material: 'Velvet',
    description: 'Luxurious velvet sharara with embossed floral pattern and contrasting dupatta. Winter-ready.',
    colors: ['Maroon', 'Navy', 'Bottle Green'], sizes: _sizes, stock: 3, rating: 4.5, reviewCount: 20,
    tags: ['sharara', 'velvet', 'winter'],
  ),
  Product(
    id: '18', name: 'Bridal Gown', price: 9000, originalPrice: 13500, discount: 33,
    imageAsset: 'assets/images/b7.jpg',
    images: ['assets/images/b7.jpg', 'assets/images/b8.jpg'],
    category: 'Bridal', material: 'Satin',
    description: 'Elegant satin bridal gown with trail and crystal embellishments.',
    colors: ['White', 'Ivory', 'Champagne'], sizes: _sizes, stock: 2, rating: 4.8, reviewCount: 35,
    tags: ['gown', 'bridal', 'satin', 'trail'],
  ),
  Product(
    id: '19', name: 'China Bridal Gown', price: 9000, originalPrice: 11000, discount: 18,
    imageAsset: 'assets/images/b8.jpg',
    images: ['assets/images/b8.jpg', 'assets/images/b9.jpg'],
    category: 'Bridal', material: 'Silk Satin',
    description: 'Fusion Indo-Chinese bridal gown with mandarin collar and side slits. Unique and stunning.',
    colors: ['Red', 'Gold', 'Black'], sizes: _sizes, stock: 4, rating: 4.3, reviewCount: 14,
    tags: ['gown', 'fusion', 'silk', 'china-style'],
  ),
  Product(
    id: '20', name: 'Marwar Couture', price: 9000, originalPrice: 14000, discount: 36,
    imageAsset: 'assets/images/B1.jpeg',
    images: ['assets/images/B1.jpeg', 'assets/images/B2.jpeg'],
    category: 'Bridal', material: 'Handloom Silk',
    description: 'Authentic Rajasthani Marwar couture with hand-block print and mirror embellishments.',
    colors: ['Orange', 'Yellow', 'Red'], sizes: _sizes, stock: 1, rating: 4.9, reviewCount: 47,
    tags: ['marwar', 'rajasthani', 'handloom', 'block-print'],
  ),
  Product(
    id: '21', name: 'Gold Dahlia Lehenga', price: 9000, originalPrice: 11000, discount: 18,
    imageAsset: 'assets/images/Gold dahlia lehenga set.jpeg',
    images: ['assets/images/Gold dahlia lehenga set.jpeg', 'assets/images/B1.jpeg'],
    category: 'Bridal', material: 'Net + Silk',
    description: 'Opulent gold dahlia lehenga set with intricate floral motifs and sequin work.',
    colors: ['Gold', 'Champagne', 'Ivory'], sizes: _sizes, stock: 3, rating: 4.7, reviewCount: 29,
    tags: ['lehenga', 'gold', 'floral', 'sequin'],
  ),
  Product(
    id: '22', name: 'Elegant Purple Embroidery', price: 9000, originalPrice: 11000, discount: 18,
    imageAsset: 'assets/images/b10.jpg',
    images: ['assets/images/b10.jpg', 'assets/images/b11.jpg'],
    category: 'Bridal', material: 'Georgette',
    description: 'Ethereal light purple georgette lehenga with thread embroidery and sequin border.',
    colors: ['Light Purple', 'Lilac', 'Lavender'], sizes: _sizes, stock: 5, rating: 4.3, reviewCount: 16,
    tags: ['lehenga', 'purple', 'embroidery', 'georgette'],
  ),
  Product(
    id: '23', name: 'Peach Cotton Silk', price: 9000, originalPrice: 10500, discount: 14,
    imageAsset: 'assets/images/b11.jpg',
    images: ['assets/images/b11.jpg', 'assets/images/b12.jpg'],
    category: 'Bridal', material: 'Cotton Silk',
    description: 'Breathable cotton silk lehenga in soothing peach tones with kantha embroidery work.',
    colors: ['Peach', 'Salmon', 'Coral'], sizes: _sizes, stock: 8, rating: 4.0, reviewCount: 10,
    tags: ['lehenga', 'cotton', 'peach', 'kantha'],
  ),
  Product(
    id: '24', name: 'Multi Colored Malbari Satin', price: 9000, originalPrice: 12000, discount: 25,
    imageAsset: 'assets/images/b12.jpg',
    images: ['assets/images/b12.jpg', 'assets/images/b13.jpg'],
    category: 'Bridal', material: 'Malbari Satin',
    description: 'Vibrant multicolored Malbari satin lehenga with patch work and mirror embellishments.',
    colors: ['Multi', 'Red-Green', 'Yellow-Blue'], sizes: _sizes, stock: 4, rating: 4.2, reviewCount: 13,
    tags: ['lehenga', 'satin', 'multicolor', 'patchwork'],
  ),
  Product(
    id: '25', name: 'Designer Thread Embroidery', price: 9000, originalPrice: 11500, discount: 22,
    imageAsset: 'assets/images/b13.jpg',
    images: ['assets/images/b13.jpg', 'assets/images/b14.jpg'],
    category: 'Bridal', material: 'Net + Silk',
    description: 'Designer lehenga with intricate thread embroidery and zardosi work. A labour of love.',
    colors: ['Red', 'Pink', 'Magenta'], sizes: _sizes, stock: 3, rating: 4.6, reviewCount: 26,
    tags: ['lehenga', 'designer', 'zardosi', 'thread-work'],
  ),
  Product(
    id: '26', name: 'Traditional Lehenga Choli', price: 9000, originalPrice: 10000, discount: 10,
    imageAsset: 'assets/images/b14.jpg',
    images: ['assets/images/b14.jpg', 'assets/images/b15.jpg'],
    category: 'Bridal', material: 'Pure Cotton',
    description: 'Classic traditional lehenga choli with bandhani print and gota patti work.',
    colors: ['Yellow', 'Orange', 'Green'], sizes: _sizes, stock: 10, rating: 4.1, reviewCount: 19,
    tags: ['lehenga', 'traditional', 'bandhani', 'gota'],
  ),
  Product(
    id: '27', name: 'Embroidery Semi Stitched', price: 9000, originalPrice: 11000, discount: 18,
    imageAsset: 'assets/images/b15.jpg',
    images: ['assets/images/b15.jpg', 'assets/images/b16.jpg'],
    category: 'Bridal', material: 'Art Silk',
    description: 'Semi-stitched art silk lehenga with heavy embroidery. Customize for a perfect fit.',
    colors: ['Green', 'Teal', 'Turquoise'], sizes: _sizes, stock: 6, rating: 4.0, reviewCount: 7,
    tags: ['lehenga', 'semi-stitched', 'art-silk', 'embroidery'],
  ),
  Product(
    id: '28', name: 'White Net Thread Embroidery', price: 9000, originalPrice: 13000, discount: 31,
    imageAsset: 'assets/images/b16.jpg',
    images: ['assets/images/b16.jpg', 'assets/images/b15.jpg'],
    category: 'Bridal', material: 'Net',
    description: 'Pristine white net lehenga with intricate white-on-white thread embroidery. Understated bridal elegance.',
    colors: ['White', 'Off-White', 'Ivory'], sizes: _sizes, stock: 2, rating: 4.7, reviewCount: 33,
    tags: ['lehenga', 'white', 'bridal', 'net', 'thread-work'],
  ),
  // ── Party Wear Collection ─────────────────────────────────────────────────
  Product(
    id: '29', name: 'A-line Gown', price: 17000, originalPrice: 20000, discount: 15,
    imageAsset: 'assets/images/p1.jpeg',
    images: ['assets/images/p1.jpeg', 'assets/images/p2.jpeg'],
    category: 'Party', material: 'Crepe',
    description: 'Sophisticated A-line gown with embellished neckline and floor-length silhouette.',
    colors: ['Navy', 'Black', 'Burgundy'], sizes: _sizes, stock: 6, rating: 4.2, reviewCount: 13,
    tags: ['gown', 'party', 'A-line', 'crepe'],
  ),
  Product(
    id: '30', name: 'Ball Gown', price: 5000, originalPrice: 7000, discount: 29,
    imageAsset: 'assets/images/p2.jpeg',
    images: ['assets/images/p2.jpeg', 'assets/images/p3.jpeg'],
    category: 'Party', material: 'Tulle',
    description: 'Fairytale ball gown in layers of soft tulle with embroidered bodice.',
    colors: ['Pink', 'Lavender', 'White'], sizes: _sizes, stock: 9, rating: 4.0, reviewCount: 8,
    tags: ['gown', 'ball', 'tulle', 'fairytale'],
  ),
  Product(
    id: '31', name: 'Party Wear Lehenga', price: 11000, originalPrice: 14000, discount: 21,
    imageAsset: 'assets/images/p3.jpeg',
    images: ['assets/images/p3.jpeg', 'assets/images/p4.jpeg'],
    category: 'Party', material: 'Georgette + Net',
    description: 'Contemporary party lehenga with digital prints and tassel detailing.',
    colors: ['Purple', 'Teal', 'Hot Pink'], sizes: _sizes, stock: 7, rating: 4.4, reviewCount: 21,
    tags: ['lehenga', 'party', 'digital-print', 'tassels'],
  ),
  Product(
    id: '32', name: 'Floral Printed Gown', price: 3000, originalPrice: 4000, discount: 25,
    imageAsset: 'assets/images/p6.jpeg',
    images: ['assets/images/p6.jpeg', 'assets/images/p7.jpeg'],
    category: 'Party', material: 'Chiffon',
    description: 'Breezy floral chiffon gown perfect for summer parties and day events.',
    colors: ['Multi', 'Pastel Pink', 'White'], sizes: _sizes, stock: 12, rating: 3.8, reviewCount: 6,
    tags: ['gown', 'floral', 'chiffon', 'summer'],
  ),
];
